save test artifacts

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,24 +11,29 @@ jobs:
       - uses: actions/checkout@v4
       - name: Install pkl
         run: brew install pkl
-      - name: select xcode version
+      - name: Select xcode version
         run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
       - uses: actions/cache@v4
         with:
-          path: ~/Library/Developer/Xcode/DerivedData
+          path: ~/Library/Developer/Xcode/DerivedData/Cosmic-*/SourcePackages/
           key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
           save-always: true
-      - name: build
+      - name: Execute build
         run: xcodebuild build -scheme "$SCHEME" -destination "$DESTINATION" CODE_SIGNING_ALLOWED='NO'
         env:
           DESTINATION: platform=macOS,arch=arm64
           SCHEME: Cosmic
-      - name: test
+      - name: Execute test
         run: xcodebuild test -resultBundlePath TestResults -scheme "$SCHEME" -destination "$DESTINATION" CODE_SIGNING_ALLOWED='NO'
         env:
           DESTINATION: platform=macOS,arch=arm64
           SCHEME: CosmicTests
-      - uses: kishikawakatsumi/xcresulttool@v1
+      - name: Archive test results
+        uses: actions/upload-artifact@v4
         with:
-          path: TestResults.xcresult
-        if: success() || failure()
+          name: TestResults
+          path: TestResults/**/*
+      # - uses: kishikawakatsumi/xcresulttool@v1
+      #   with:
+      #     path: TestResults.xcresult
+      #   if: success() || failure()
